# Write your query or mutation here
fragment image on UploadFile {
  alternativeText
  url
}

fragment cover on Post {
  cover {
    data {
      id
      attributes {
        ...image
      }
    }
  }
}

fragment tag on Tag {
  displayName
  slug
}

fragment author on Author {
  displayName
  slug
}

fragment category on Category {
  displayName
  slug
}

fragment tags on Post {
  tags {
    data {
      id
      attributes {
        ...tag
      }
    }
  }
}

fragment authorPost on Post {
  author {
    data {
      id
      attributes {
        ...author
      }
    }
  }
}

fragment categories on Post {
  categories {
    data {
      id
      attributes {
        ...category
      }
    }
  }
}

fragment menuLink on ComponentMenuMenuLink {
  id
  link
  text
  newTab
}

fragment post on Post {
  slug
  title
  excerpt
  content
  allowComments
  ...cover
  ...categories
  ...tags
  ...authorPost
}

fragment settings on Setting {
  blogName
  blogDescription
  logo {
    data {
      attributes {
        ...image
      }
    }
  }
  menuLink {
    ...menuLink
  }
}

query GET_POSTS {
  setting {
    data {
      id
      attributes {
        ...settings
      }
    }
  }

  posts {
    data {
      attributes {
        ...post
      }
    }
  }
}

query GET_POST_BY_SLUG($postSlug: StringFilterInput) {
  setting {
    data {
      id

      attributes {
        ...settings
      }
    }
  }
  posts(filters: { slug: $postSlug }) {
    data {
      attributes {
        ...post
      }
    }
  }
}

query GET_POSTS_BY_AUTHOR($authorSlug: StringFilterInput) {
  setting {
    data {
      id

      attributes {
        ...settings
      }
    }
  }

  posts(filters: { author: { slug: $authorSlug } }) {
    data {
      attributes {
        ...authorPost
      }
    }
  }
}

query GET_POSTS_BY_CATEGORY($categorySlug: StringFilterInput) {
  setting {
    data {
      id

      attributes {
        ...settings
      }
    }
  }

  posts(filters: { categories: { slug: $categorySlug } }) {
    data {
      attributes {
        ...post
      }
    }
  }
}

query GET_POSTS_BY_TAGS($tagSlug: StringFilterInput!) {
  setting {
    data {
      id

      attributes {
        ...settings
      }
    }
  }

  posts(filters: { tags: { slug: $tagSlug } }) {
    data {
      attributes {
        ...post
      }
    }
  }
}
